/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tem.geopen;

/**
 *
 * @author Administrator
 */
public class TEMClockDialog extends javax.swing.JDialog {

    TEMAcquisitionProMain frame;

    /**
     * Creates new form CSAMTClockDialog
     */
    public TEMClockDialog(TEMAcquisitionProMain parent, boolean modal) {
        super(parent, modal);
        this.frame = parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        waitingProgressBar = new javax.swing.JProgressBar();
        freshButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        waitingProgressBar.setIndeterminate(true);
        waitingProgressBar.setString("等待。。。");
        waitingProgressBar.setStringPainted(true);

        freshButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/geopen/fresh16.png"))); // NOI18N
        freshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freshButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(waitingProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(freshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(freshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(waitingProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {freshButton, waitingProgressBar});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void freshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freshButtonActionPerformed
        // TODO add your handling code here:
        frame.fresh();
    }//GEN-LAST:event_freshButtonActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton freshButton;
    public javax.swing.JProgressBar waitingProgressBar;
    // End of variables declaration//GEN-END:variables
}
