/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tem.geopen;

import java.awt.Dimension;
import java.awt.Point;
import java.awt.Rectangle;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.SwingWorker;

/**
 *
 * @author Administrator
 */
public class WaitingResisDialog extends javax.swing.JDialog implements PropertyChangeListener {

    TEMAcquisitionProMain frame;
    int value = 100;
    Task task = new Task();

    /**
     * Creates new form WaitingResisDialog
     */
    public WaitingResisDialog(TEMAcquisitionProMain frame, boolean modal) {
        super(frame, modal);
        initComponents();
        this.frame = frame;
        pack();
        Rectangle parentBounds = frame.getBounds();
        Dimension size = getSize();
        int x = Math.max(0, parentBounds.x + (parentBounds.width - size.width) / 2);
        int y = Math.max(0, parentBounds.y + (parentBounds.height - size.height) / 2);
        setLocation(new Point(x, y));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        waitingProfressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        waitingProfressBar.setMaximum(10);
        waitingProfressBar.setValue(10);
        waitingProfressBar.setString("");
        waitingProfressBar.setStringPainted(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(waitingProfressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(waitingProfressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar waitingProfressBar;
    // End of variables declaration//GEN-END:variables

    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        if ("progress" == evt.getPropertyName()) {
            int progress = (Integer) evt.getNewValue();
            waitingProfressBar.setValue(progress);
            waitingProfressBar.setString("等待子站响应_剩余时间：" + progress + "s");
        }
    }

    /**
     * 更新窗口类
     */
    class Task extends SwingWorker<Void, Void> {

        public Void doInBackground() {
            setProgress(10);//现设初始值
            for (int i = 9; i >= 0; i--) {
                try {
                    Thread.sleep(1000);
                    value = i;
                    setProgress(value);
                } catch (InterruptedException ex) {
                }
            }
            return null;
        }

        public void done() {
            if (value == 0) {
                frame.fresh();//还原
                dispose();
            }
        }
    }
}
